{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "meraki-root-cause.serviceAccountName" . }}
  labels:
{{ include "meraki-root-cause.labels" . | indent 4 }}
{{- end -}}
